package com.jy.entity.jc.user;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;

import java.util.Date;

@Alias("UserAddress")
public class UserAddress extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_address.addressId
     *
     * @mbggenerated
     */
    private String addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_address.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_address.addressee
     *
     * @mbggenerated
     */
    private String addressee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_address.contact
     *
     * @mbggenerated
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_address.region
     *
     * @mbggenerated
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_address.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_address.isDefault
     *
     * @mbggenerated
     */
    private Integer isdefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_address.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_address.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_address.addressId
     *
     * @return the value of jc_user_address.addressId
     *
     * @mbggenerated
     */
    public String getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_address.addressId
     *
     * @param addressid the value for jc_user_address.addressId
     *
     * @mbggenerated
     */
    public void setAddressid(String addressid) {
        this.addressid = addressid == null ? null : addressid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_address.user_id
     *
     * @return the value of jc_user_address.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_address.user_id
     *
     * @param userId the value for jc_user_address.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_address.addressee
     *
     * @return the value of jc_user_address.addressee
     *
     * @mbggenerated
     */
    public String getAddressee() {
        return addressee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_address.addressee
     *
     * @param addressee the value for jc_user_address.addressee
     *
     * @mbggenerated
     */
    public void setAddressee(String addressee) {
        this.addressee = addressee == null ? null : addressee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_address.contact
     *
     * @return the value of jc_user_address.contact
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_address.contact
     *
     * @param contact the value for jc_user_address.contact
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_address.region
     *
     * @return the value of jc_user_address.region
     *
     * @mbggenerated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_address.region
     *
     * @param region the value for jc_user_address.region
     *
     * @mbggenerated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_address.address
     *
     * @return the value of jc_user_address.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_address.address
     *
     * @param address the value for jc_user_address.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_address.isDefault
     *
     * @return the value of jc_user_address.isDefault
     *
     * @mbggenerated
     */
    public Integer getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_address.isDefault
     *
     * @param isdefault the value for jc_user_address.isDefault
     *
     * @mbggenerated
     */
    public void setIsdefault(Integer isdefault) {
        this.isdefault = isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_address.createTime
     *
     * @return the value of jc_user_address.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_address.createTime
     *
     * @param createtime the value for jc_user_address.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_address.updateTime
     *
     * @return the value of jc_user_address.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_address.updateTime
     *
     * @param updatetime the value for jc_user_address.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}