package com.jy.repository.jc.match;


import com.jy.entity.jc.match.JcMatchResult;
import com.jy.repository.base.BaseDao;
import com.jy.repository.base.JYBatis;

@JYBatis
public interface JcMatchResultMapper  extends BaseDao<JcMatchResult> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_match_result
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String matchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_match_result
     *
     * @mbggenerated
     */
    int insertSelective(JcMatchResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_match_result
     *
     * @mbggenerated
     */
    JcMatchResult selectByPrimaryKey(String matchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_match_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JcMatchResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_match_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(JcMatchResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_match_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JcMatchResult record);
}