package com.jy.entity.jc.groundercomplain;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

@Alias("GrounderComplain")
public class GrounderComplain extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_complain.complain_id
     *
     * @mbggenerated
     */
    private String complainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_complain.grounder_id
     *
     * @mbggenerated
     */
    private String grounderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_complain.compained_user_id
     *
     * @mbggenerated
     */
    private String compainedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_complain.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_complain.state
     *
     * @mbggenerated
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_complain.reply_content
     *
     * @mbggenerated
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_complain.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_complain.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_complain.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_complain.complain_id
     *
     * @return the value of jc_grounder_complain.complain_id
     *
     * @mbggenerated
     */
    public String getComplainId() {
        return complainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_complain.complain_id
     *
     * @param complainId the value for jc_grounder_complain.complain_id
     *
     * @mbggenerated
     */
    public void setComplainId(String complainId) {
        this.complainId = complainId == null ? null : complainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_complain.grounder_id
     *
     * @return the value of jc_grounder_complain.grounder_id
     *
     * @mbggenerated
     */
    public String getGrounderId() {
        return grounderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_complain.grounder_id
     *
     * @param grounderId the value for jc_grounder_complain.grounder_id
     *
     * @mbggenerated
     */
    public void setGrounderId(String grounderId) {
        this.grounderId = grounderId == null ? null : grounderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_complain.compained_user_id
     *
     * @return the value of jc_grounder_complain.compained_user_id
     *
     * @mbggenerated
     */
    public String getCompainedUserId() {
        return compainedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_complain.compained_user_id
     *
     * @param compainedUserId the value for jc_grounder_complain.compained_user_id
     *
     * @mbggenerated
     */
    public void setCompainedUserId(String compainedUserId) {
        this.compainedUserId = compainedUserId == null ? null : compainedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_complain.user_id
     *
     * @return the value of jc_grounder_complain.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_complain.user_id
     *
     * @param userId the value for jc_grounder_complain.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_complain.state
     *
     * @return the value of jc_grounder_complain.state
     *
     * @mbggenerated
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_complain.state
     *
     * @param state the value for jc_grounder_complain.state
     *
     * @mbggenerated
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_complain.reply_content
     *
     * @return the value of jc_grounder_complain.reply_content
     *
     * @mbggenerated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_complain.reply_content
     *
     * @param replyContent the value for jc_grounder_complain.reply_content
     *
     * @mbggenerated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_complain.oper_id
     *
     * @return the value of jc_grounder_complain.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_complain.oper_id
     *
     * @param operId the value for jc_grounder_complain.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_complain.create_time
     *
     * @return the value of jc_grounder_complain.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_complain.create_time
     *
     * @param createTime the value for jc_grounder_complain.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_complain.update_time
     *
     * @return the value of jc_grounder_complain.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_complain.update_time
     *
     * @param updateTime the value for jc_grounder_complain.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}