package com.jy.entity.jc.match;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;

import java.util.Date;

@Alias("JcMatchResult")
public class JcMatchResult extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_result.match_id
     *
     * @mbggenerated
     */
    private String matchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_result.match_type
     *
     * @mbggenerated
     */
    private Short matchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_result.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_result.state
     *
     * @mbggenerated
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_result.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_result.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_result.error_msg
     *
     * @mbggenerated
     */
    private String errorMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_result.match_id
     *
     * @return the value of jc_match_result.match_id
     *
     * @mbggenerated
     */
    public String getMatchId() {
        return matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_result.match_id
     *
     * @param matchId the value for jc_match_result.match_id
     *
     * @mbggenerated
     */
    public void setMatchId(String matchId) {
        this.matchId = matchId == null ? null : matchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_result.match_type
     *
     * @return the value of jc_match_result.match_type
     *
     * @mbggenerated
     */
    public Short getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_result.match_type
     *
     * @param matchType the value for jc_match_result.match_type
     *
     * @mbggenerated
     */
    public void setMatchType(Short matchType) {
        this.matchType = matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_result.file_name
     *
     * @return the value of jc_match_result.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_result.file_name
     *
     * @param fileName the value for jc_match_result.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_result.state
     *
     * @return the value of jc_match_result.state
     *
     * @mbggenerated
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_result.state
     *
     * @param state the value for jc_match_result.state
     *
     * @mbggenerated
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_result.create_time
     *
     * @return the value of jc_match_result.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_result.create_time
     *
     * @param createTime the value for jc_match_result.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_result.update_time
     *
     * @return the value of jc_match_result.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_result.update_time
     *
     * @param updateTime the value for jc_match_result.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_result.error_msg
     *
     * @return the value of jc_match_result.error_msg
     *
     * @mbggenerated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_result.error_msg
     *
     * @param errorMsg the value for jc_match_result.error_msg
     *
     * @mbggenerated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }
}