package com.jy.entity.jc.betbill;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Alias("BetBill")
public class BetBill extends BaseEntity{

    private Integer realBonus; //实际奖金


    private List<BetDetail> detailList = new ArrayList<>();


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.bet_id
     *
     * @mbggenerated
     */
    private String betId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.account_log_id
     *
     * @mbggenerated
     */
    private String accountLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.items
     *
     * @mbggenerated
     */
    private Integer items;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.bonus
     *
     * @mbggenerated
     */
    private Integer bonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.bunch
     *
     * @mbggenerated
     */
    private String bunch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.match_type
     *
     * @mbggenerated
     */
    private Short matchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.iscorrect
     *
     * @mbggenerated
     */
    private Integer iscorrect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_bill.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.bet_id
     *
     * @return the value of jc_bet_bill.bet_id
     *
     * @mbggenerated
     */
    public String getBetId() {
        return betId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.bet_id
     *
     * @param betId the value for jc_bet_bill.bet_id
     *
     * @mbggenerated
     */
    public void setBetId(String betId) {
        this.betId = betId == null ? null : betId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.user_id
     *
     * @return the value of jc_bet_bill.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.user_id
     *
     * @param userId the value for jc_bet_bill.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.account_log_id
     *
     * @return the value of jc_bet_bill.account_log_id
     *
     * @mbggenerated
     */
    public String getAccountLogId() {
        return accountLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.account_log_id
     *
     * @param accountLogId the value for jc_bet_bill.account_log_id
     *
     * @mbggenerated
     */
    public void setAccountLogId(String accountLogId) {
        this.accountLogId = accountLogId == null ? null : accountLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.amount
     *
     * @return the value of jc_bet_bill.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.amount
     *
     * @param amount the value for jc_bet_bill.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.items
     *
     * @return the value of jc_bet_bill.items
     *
     * @mbggenerated
     */
    public Integer getItems() {
        return items;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.items
     *
     * @param items the value for jc_bet_bill.items
     *
     * @mbggenerated
     */
    public void setItems(Integer items) {
        this.items = items;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.bonus
     *
     * @return the value of jc_bet_bill.bonus
     *
     * @mbggenerated
     */
    public Integer getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.bonus
     *
     * @param bonus the value for jc_bet_bill.bonus
     *
     * @mbggenerated
     */
    public void setBonus(Integer bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.bunch
     *
     * @return the value of jc_bet_bill.bunch
     *
     * @mbggenerated
     */
    public String getBunch() {
        return bunch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.bunch
     *
     * @param bunch the value for jc_bet_bill.bunch
     *
     * @mbggenerated
     */
    public void setBunch(String bunch) {
        this.bunch = bunch == null ? null : bunch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.match_type
     *
     * @return the value of jc_bet_bill.match_type
     *
     * @mbggenerated
     */
    public Short getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.match_type
     *
     * @param matchType the value for jc_bet_bill.match_type
     *
     * @mbggenerated
     */
    public void setMatchType(Short matchType) {
        this.matchType = matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.status
     *
     * @return the value of jc_bet_bill.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.status
     *
     * @param status the value for jc_bet_bill.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.iscorrect
     *
     * @return the value of jc_bet_bill.iscorrect
     *
     * @mbggenerated
     */
    public Integer getIscorrect() {
        return iscorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.iscorrect
     *
     * @param iscorrect the value for jc_bet_bill.iscorrect
     *
     * @mbggenerated
     */
    public void setIscorrect(Integer iscorrect) {
        this.iscorrect = iscorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.create_time
     *
     * @return the value of jc_bet_bill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.create_time
     *
     * @param createTime the value for jc_bet_bill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_bill.update_time
     *
     * @return the value of jc_bet_bill.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_bill.update_time
     *
     * @param updateTime the value for jc_bet_bill.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public List<BetDetail> getDetailList() {
        return detailList;
    }

    public void setDetailList(List<BetDetail> detailList) {
        this.detailList = detailList;
    }

    public Integer getRealBonus() {
        return realBonus;
    }

    public void setRealBonus(Integer realBonus) {
        this.realBonus = realBonus;
    }
}