package com.jy.entity.jc.betbill;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;

@Alias("BetDetail")
public class BetDetail extends BaseEntity{

    private Short betType; //玩法

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_detail.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_detail.bet_id
     *
     * @mbggenerated
     */
    private String betId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_detail.match_id
     *
     * @mbggenerated
     */
    private String matchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_detail.match_game_id
     *
     * @mbggenerated
     */
    private String matchGameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_detail.bet_select
     *
     * @mbggenerated
     */
    private String betSelect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_bet_detail.state
     *
     * @mbggenerated
     */
    private Short state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_detail.order_id
     *
     * @return the value of jc_bet_detail.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_detail.order_id
     *
     * @param orderId the value for jc_bet_detail.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_detail.bet_id
     *
     * @return the value of jc_bet_detail.bet_id
     *
     * @mbggenerated
     */
    public String getBetId() {
        return betId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_detail.bet_id
     *
     * @param betId the value for jc_bet_detail.bet_id
     *
     * @mbggenerated
     */
    public void setBetId(String betId) {
        this.betId = betId == null ? null : betId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_detail.match_id
     *
     * @return the value of jc_bet_detail.match_id
     *
     * @mbggenerated
     */
    public String getMatchId() {
        return matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_detail.match_id
     *
     * @param matchId the value for jc_bet_detail.match_id
     *
     * @mbggenerated
     */
    public void setMatchId(String matchId) {
        this.matchId = matchId == null ? null : matchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_detail.match_game_id
     *
     * @return the value of jc_bet_detail.match_game_id
     *
     * @mbggenerated
     */
    public String getMatchGameId() {
        return matchGameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_detail.match_game_id
     *
     * @param matchGameId the value for jc_bet_detail.match_game_id
     *
     * @mbggenerated
     */
    public void setMatchGameId(String matchGameId) {
        this.matchGameId = matchGameId == null ? null : matchGameId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_detail.bet_select
     *
     * @return the value of jc_bet_detail.bet_select
     *
     * @mbggenerated
     */
    public String getBetSelect() {
        return betSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_detail.bet_select
     *
     * @param betSelect the value for jc_bet_detail.bet_select
     *
     * @mbggenerated
     */
    public void setBetSelect(String betSelect) {
        this.betSelect = betSelect == null ? null : betSelect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_bet_detail.state
     *
     * @return the value of jc_bet_detail.state
     *
     * @mbggenerated
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_bet_detail.state
     *
     * @param state the value for jc_bet_detail.state
     *
     * @mbggenerated
     */
    public void setState(Short state) {
        this.state = state;
    }

    public Short getBetType() {
        return betType;
    }

    public void setBetType(Short betType) {
        this.betType = betType;
    }
}