package com.jy.entity.jc.recommendbill;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;
@Alias("RecommendBill")
public class RecommendBill extends BaseEntity{

    private Integer state;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_bill.recommend_id
     *
     * @mbggenerated
     */
    private String recommendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_bill.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_bill.bunch
     *
     * @mbggenerated
     */
    private String bunch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_bill.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_bill.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_bill.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_bill.match_type
     *
     * @mbggenerated
     */
    private Short matchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_bill.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_bill.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_bill.profit_rate
     *
     * @mbggenerated
     */
    private BigDecimal profitRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_bill.recommend_id
     *
     * @return the value of jc_recommend_bill.recommend_id
     *
     * @mbggenerated
     */
    public String getRecommendId() {
        return recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_bill.recommend_id
     *
     * @param recommendId the value for jc_recommend_bill.recommend_id
     *
     * @mbggenerated
     */
    public void setRecommendId(String recommendId) {
        this.recommendId = recommendId == null ? null : recommendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_bill.user_id
     *
     * @return the value of jc_recommend_bill.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_bill.user_id
     *
     * @param userId the value for jc_recommend_bill.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_bill.bunch
     *
     * @return the value of jc_recommend_bill.bunch
     *
     * @mbggenerated
     */
    public String getBunch() {
        return bunch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_bill.bunch
     *
     * @param bunch the value for jc_recommend_bill.bunch
     *
     * @mbggenerated
     */
    public void setBunch(String bunch) {
        this.bunch = bunch == null ? null : bunch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_bill.price
     *
     * @return the value of jc_recommend_bill.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_bill.price
     *
     * @param price the value for jc_recommend_bill.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_bill.title
     *
     * @return the value of jc_recommend_bill.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_bill.title
     *
     * @param title the value for jc_recommend_bill.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_bill.reason
     *
     * @return the value of jc_recommend_bill.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_bill.reason
     *
     * @param reason the value for jc_recommend_bill.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_bill.match_type
     *
     * @return the value of jc_recommend_bill.match_type
     *
     * @mbggenerated
     */
    public Short getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_bill.match_type
     *
     * @param matchType the value for jc_recommend_bill.match_type
     *
     * @mbggenerated
     */
    public void setMatchType(Short matchType) {
        this.matchType = matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_bill.create_time
     *
     * @return the value of jc_recommend_bill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_bill.create_time
     *
     * @param createTime the value for jc_recommend_bill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_bill.update_time
     *
     * @return the value of jc_recommend_bill.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_bill.update_time
     *
     * @param updateTime the value for jc_recommend_bill.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_bill.profit_rate
     *
     * @return the value of jc_recommend_bill.profit_rate
     *
     * @mbggenerated
     */
    public BigDecimal getProfitRate() {
        return profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_bill.profit_rate
     *
     * @param profitRate the value for jc_recommend_bill.profit_rate
     *
     * @mbggenerated
     */
    public void setProfitRate(BigDecimal profitRate) {
        this.profitRate = profitRate;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }
}