package com.jy.entity.jc.messagecenter;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;

@Alias("MessageReceiver")
public class MessageReceiver extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_message_receiver.msg_id
     *
     * @mbggenerated
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_message_receiver.receiver
     *
     * @mbggenerated
     */
    private String receiver;
    private String mobile;
    private String realName;
    private String nickName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_message_receiver.msg_id
     *
     * @return the value of jc_message_receiver.msg_id
     *
     * @mbggenerated
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_message_receiver.msg_id
     *
     * @param msgId the value for jc_message_receiver.msg_id
     *
     * @mbggenerated
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId == null ? null : msgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_message_receiver.receiver
     *
     * @return the value of jc_message_receiver.receiver
     *
     * @mbggenerated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_message_receiver.receiver
     *
     * @param receiver the value for jc_message_receiver.receiver
     *
     * @mbggenerated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
}