package com.jy.entity.jc.recommenddetail;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;

@Alias("RecommendDetail")
public class RecommendDetail extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.recommend_id
     *
     * @mbggenerated
     */
    private String recommendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.match_id
     *
     * @mbggenerated
     */
    private String matchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.bet_type
     *
     * @mbggenerated
     */
    private Short matchGameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.guess_result
     *
     * @mbggenerated
     */
    private Short guessResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.match_preview
     *
     * @mbggenerated
     */
    private String matchPreview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.strength_ratio
     *
     * @mbggenerated
     */
    private String strengthRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.strength_desc
     *
     * @mbggenerated
     */
    private String strengthDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.data_ratio
     *
     * @mbggenerated
     */
    private String dataRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.data_desc
     *
     * @mbggenerated
     */
    private String dataDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.expert_comments
     *
     * @mbggenerated
     */
    private String expertComments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.tech_statis
     *
     * @mbggenerated
     */
    private String techStatis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_recommend_detail.profit_rate
     *
     * @mbggenerated
     */
    private BigDecimal profitRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.recommend_id
     *
     * @return the value of jc_recommend_detail.recommend_id
     *
     * @mbggenerated
     */
    public String getRecommendId() {
        return recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.recommend_id
     *
     * @param recommendId the value for jc_recommend_detail.recommend_id
     *
     * @mbggenerated
     */
    public void setRecommendId(String recommendId) {
        this.recommendId = recommendId == null ? null : recommendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.match_id
     *
     * @return the value of jc_recommend_detail.match_id
     *
     * @mbggenerated
     */
    public String getMatchId() {
        return matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.match_id
     *
     * @param matchId the value for jc_recommend_detail.match_id
     *
     * @mbggenerated
     */
    public void setMatchId(String matchId) {
        this.matchId = matchId == null ? null : matchId.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.guess_result
     *
     * @return the value of jc_recommend_detail.guess_result
     *
     * @mbggenerated
     */
    public Short getGuessResult() {
        return guessResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.guess_result
     *
     * @param guessResult the value for jc_recommend_detail.guess_result
     *
     * @mbggenerated
     */
    public void setGuessResult(Short guessResult) {
        this.guessResult = guessResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.match_preview
     *
     * @return the value of jc_recommend_detail.match_preview
     *
     * @mbggenerated
     */
    public String getMatchPreview() {
        return matchPreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.match_preview
     *
     * @param matchPreview the value for jc_recommend_detail.match_preview
     *
     * @mbggenerated
     */
    public void setMatchPreview(String matchPreview) {
        this.matchPreview = matchPreview == null ? null : matchPreview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.strength_ratio
     *
     * @return the value of jc_recommend_detail.strength_ratio
     *
     * @mbggenerated
     */
    public String getStrengthRatio() {
        return strengthRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.strength_ratio
     *
     * @param strengthRatio the value for jc_recommend_detail.strength_ratio
     *
     * @mbggenerated
     */
    public void setStrengthRatio(String strengthRatio) {
        this.strengthRatio = strengthRatio == null ? null : strengthRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.strength_desc
     *
     * @return the value of jc_recommend_detail.strength_desc
     *
     * @mbggenerated
     */
    public String getStrengthDesc() {
        return strengthDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.strength_desc
     *
     * @param strengthDesc the value for jc_recommend_detail.strength_desc
     *
     * @mbggenerated
     */
    public void setStrengthDesc(String strengthDesc) {
        this.strengthDesc = strengthDesc == null ? null : strengthDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.data_ratio
     *
     * @return the value of jc_recommend_detail.data_ratio
     *
     * @mbggenerated
     */
    public String getDataRatio() {
        return dataRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.data_ratio
     *
     * @param dataRatio the value for jc_recommend_detail.data_ratio
     *
     * @mbggenerated
     */
    public void setDataRatio(String dataRatio) {
        this.dataRatio = dataRatio == null ? null : dataRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.data_desc
     *
     * @return the value of jc_recommend_detail.data_desc
     *
     * @mbggenerated
     */
    public String getDataDesc() {
        return dataDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.data_desc
     *
     * @param dataDesc the value for jc_recommend_detail.data_desc
     *
     * @mbggenerated
     */
    public void setDataDesc(String dataDesc) {
        this.dataDesc = dataDesc == null ? null : dataDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.expert_comments
     *
     * @return the value of jc_recommend_detail.expert_comments
     *
     * @mbggenerated
     */
    public String getExpertComments() {
        return expertComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.expert_comments
     *
     * @param expertComments the value for jc_recommend_detail.expert_comments
     *
     * @mbggenerated
     */
    public void setExpertComments(String expertComments) {
        this.expertComments = expertComments == null ? null : expertComments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.tech_statis
     *
     * @return the value of jc_recommend_detail.tech_statis
     *
     * @mbggenerated
     */
    public String getTechStatis() {
        return techStatis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.tech_statis
     *
     * @param techStatis the value for jc_recommend_detail.tech_statis
     *
     * @mbggenerated
     */
    public void setTechStatis(String techStatis) {
        this.techStatis = techStatis == null ? null : techStatis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_recommend_detail.profit_rate
     *
     * @return the value of jc_recommend_detail.profit_rate
     *
     * @mbggenerated
     */
    public BigDecimal getProfitRate() {
        return profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_recommend_detail.profit_rate
     *
     * @param profitRate the value for jc_recommend_detail.profit_rate
     *
     * @mbggenerated
     */
    public void setProfitRate(BigDecimal profitRate) {
        this.profitRate = profitRate;
    }

    public Short getMatchGameId() {
        return matchGameId;
    }

    public void setMatchGameId(Short matchGameId) {
        this.matchGameId = matchGameId;
    }
}