package com.jy.entity.jc.groundebill;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

@Alias("GrounderBill")
public class GrounderBill extends BaseEntity{

    private Integer state;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_bill.grounder_id
     *
     * @mbggenerated
     */
    private String grounderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_bill.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_bill.match_id
     *
     * @mbggenerated
     */
    private String matchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_bill.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_bill.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_bill.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_bill.match_type
     *
     * @mbggenerated
     */
    private Short matchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_bill.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_grounder_bill.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_bill.grounder_id
     *
     * @return the value of jc_grounder_bill.grounder_id
     *
     * @mbggenerated
     */
    public String getGrounderId() {
        return grounderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_bill.grounder_id
     *
     * @param grounderId the value for jc_grounder_bill.grounder_id
     *
     * @mbggenerated
     */
    public void setGrounderId(String grounderId) {
        this.grounderId = grounderId == null ? null : grounderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_bill.user_id
     *
     * @return the value of jc_grounder_bill.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_bill.user_id
     *
     * @param userId the value for jc_grounder_bill.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_bill.match_id
     *
     * @return the value of jc_grounder_bill.match_id
     *
     * @mbggenerated
     */
    public String getMatchId() {
        return matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_bill.match_id
     *
     * @param matchId the value for jc_grounder_bill.match_id
     *
     * @mbggenerated
     */
    public void setMatchId(String matchId) {
        this.matchId = matchId == null ? null : matchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_bill.price
     *
     * @return the value of jc_grounder_bill.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_bill.price
     *
     * @param price the value for jc_grounder_bill.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_bill.title
     *
     * @return the value of jc_grounder_bill.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_bill.title
     *
     * @param title the value for jc_grounder_bill.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_bill.content
     *
     * @return the value of jc_grounder_bill.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_bill.content
     *
     * @param content the value for jc_grounder_bill.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_bill.match_type
     *
     * @return the value of jc_grounder_bill.match_type
     *
     * @mbggenerated
     */
    public Short getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_bill.match_type
     *
     * @param matchType the value for jc_grounder_bill.match_type
     *
     * @mbggenerated
     */
    public void setMatchType(Short matchType) {
        this.matchType = matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_bill.create_time
     *
     * @return the value of jc_grounder_bill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_bill.create_time
     *
     * @param createTime the value for jc_grounder_bill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_grounder_bill.update_time
     *
     * @return the value of jc_grounder_bill.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_grounder_bill.update_time
     *
     * @param updateTime the value for jc_grounder_bill.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }
}