package com.jy.entity.jc.userrecommendrel;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;

import java.util.Date;

@Alias("UserRecommendRel")
public class UserRecommendRel extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_recommend_rel.account_log_id
     *
     * @mbggenerated
     */
    private String accountLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_recommend_rel.recommend_id
     *
     * @mbggenerated
     */
    private String recommendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_recommend_rel.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_recommend_rel.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_recommend_rel.account_log_id
     *
     * @return the value of jc_user_recommend_rel.account_log_id
     *
     * @mbggenerated
     */
    public String getAccountLogId() {
        return accountLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_recommend_rel.account_log_id
     *
     * @param accountLogId the value for jc_user_recommend_rel.account_log_id
     *
     * @mbggenerated
     */
    public void setAccountLogId(String accountLogId) {
        this.accountLogId = accountLogId == null ? null : accountLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_recommend_rel.recommend_id
     *
     * @return the value of jc_user_recommend_rel.recommend_id
     *
     * @mbggenerated
     */
    public String getRecommendId() {
        return recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_recommend_rel.recommend_id
     *
     * @param recommendId the value for jc_user_recommend_rel.recommend_id
     *
     * @mbggenerated
     */
    public void setRecommendId(String recommendId) {
        this.recommendId = recommendId == null ? null : recommendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_recommend_rel.user_id
     *
     * @return the value of jc_user_recommend_rel.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_recommend_rel.user_id
     *
     * @param userId the value for jc_user_recommend_rel.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_recommend_rel.create_time
     *
     * @return the value of jc_user_recommend_rel.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_recommend_rel.create_time
     *
     * @param createTime the value for jc_user_recommend_rel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}