package com.jy.entity.jc.paintedEgg;

import java.util.Date;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;
@Alias("PaintedEggUser")
public class PaintedEggUser extends BaseEntity{
    @Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PaintedEggUser [timeCount=");
		builder.append(timeCount);
		builder.append(", answerId=");
		builder.append(answerId);
		builder.append(", egguserlogid=");
		builder.append(egguserlogid);
		builder.append(", eggid=");
		builder.append(eggid);
		builder.append(", nick_name=");
		builder.append(nick_name);
		builder.append(", userId=");
		builder.append(userId);
		builder.append(", accountLogId=");
		builder.append(accountLogId);
		builder.append(", luckynumstart=");
		builder.append(luckynumstart);
		builder.append(", luckynumend=");
		builder.append(luckynumend);
		builder.append(", totalcnt=");
		builder.append(totalcnt);
		builder.append(", isright=");
		builder.append(isright);
		builder.append(", createtime=");
		builder.append(createtime);
		builder.append(", updatetime=");
		builder.append(updatetime);
		builder.append("]");
		return builder.toString();
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_user.eggUserLogId
     *
     * @mbggenerated
     * 
     * 
     */
	private long timeCount;
	public long getTimeCount() {
		return timeCount;
	}

	public void setTimeCount(long timeCount) {
		this.timeCount = timeCount;
	}

	private String answerId;
    public String getAnswerId() {
		return answerId;
	}

	public void setAnswerId(String answerId) {
		this.answerId = answerId;
	}

	private String egguserlogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_user.eggId
     *
     * @mbggenerated
     */
    private String eggid;
    
    private String  nick_name;

    public String getNick_name() {
		return nick_name;
	}

	public void setNick_name(String nick_name) {
		this.nick_name = nick_name;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_user.account_log_id
     *
     * @mbggenerated
     */
    private String accountLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_user.luckyNumStart
     *
     * @mbggenerated
     */
    private Integer luckynumstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_user.luckyNumEnd
     *
     * @mbggenerated
     */
    private Integer luckynumend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_user.totalCnt
     *
     * @mbggenerated
     */
    private Integer totalcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_user.isRight
     *
     * @mbggenerated
     */
    private Integer isright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_user.createTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_user.updateTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_user.eggUserLogId
     *
     * @return the value of jc_painted_egg_user.eggUserLogId
     *
     * @mbggenerated
     */
    public String getEgguserlogid() {
        return egguserlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_user.eggUserLogId
     *
     * @param egguserlogid the value for jc_painted_egg_user.eggUserLogId
     *
     * @mbggenerated
     */
    public void setEgguserlogid(String egguserlogid) {
        this.egguserlogid = egguserlogid == null ? null : egguserlogid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_user.eggId
     *
     * @return the value of jc_painted_egg_user.eggId
     *
     * @mbggenerated
     */
    public String getEggid() {
        return eggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_user.eggId
     *
     * @param eggid the value for jc_painted_egg_user.eggId
     *
     * @mbggenerated
     */
    public void setEggid(String eggid) {
        this.eggid = eggid == null ? null : eggid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_user.user_id
     *
     * @return the value of jc_painted_egg_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_user.user_id
     *
     * @param userId the value for jc_painted_egg_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_user.account_log_id
     *
     * @return the value of jc_painted_egg_user.account_log_id
     *
     * @mbggenerated
     */
    public String getAccountLogId() {
        return accountLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_user.account_log_id
     *
     * @param accountLogId the value for jc_painted_egg_user.account_log_id
     *
     * @mbggenerated
     */
    public void setAccountLogId(String accountLogId) {
        this.accountLogId = accountLogId == null ? null : accountLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_user.luckyNumStart
     *
     * @return the value of jc_painted_egg_user.luckyNumStart
     *
     * @mbggenerated
     */
    public Integer getLuckynumstart() {
        return luckynumstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_user.luckyNumStart
     *
     * @param luckynumstart the value for jc_painted_egg_user.luckyNumStart
     *
     * @mbggenerated
     */
    public void setLuckynumstart(Integer luckynumstart) {
        this.luckynumstart = luckynumstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_user.luckyNumEnd
     *
     * @return the value of jc_painted_egg_user.luckyNumEnd
     *
     * @mbggenerated
     */
    public Integer getLuckynumend() {
        return luckynumend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_user.luckyNumEnd
     *
     * @param luckynumend the value for jc_painted_egg_user.luckyNumEnd
     *
     * @mbggenerated
     */
    public void setLuckynumend(Integer luckynumend) {
        this.luckynumend = luckynumend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_user.totalCnt
     *
     * @return the value of jc_painted_egg_user.totalCnt
     *
     * @mbggenerated
     */
    public Integer getTotalcnt() {
        return totalcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_user.totalCnt
     *
     * @param totalcnt the value for jc_painted_egg_user.totalCnt
     *
     * @mbggenerated
     */
    public void setTotalcnt(Integer totalcnt) {
        this.totalcnt = totalcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_user.isRight
     *
     * @return the value of jc_painted_egg_user.isRight
     *
     * @mbggenerated
     */
    public Integer getIsright() {
        return isright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_user.isRight
     *
     * @param isright the value for jc_painted_egg_user.isRight
     *
     * @mbggenerated
     */
    public void setIsright(Integer isright) {
        this.isright = isright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_user.createTime
     *
     * @return the value of jc_painted_egg_user.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_user.createTime
     *
     * @param createtime the value for jc_painted_egg_user.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_user.updateTime
     *
     * @return the value of jc_painted_egg_user.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_user.updateTime
     *
     * @param updatetime the value for jc_painted_egg_user.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}