package com.jy.entity.jc.paintedEgg;


import java.util.Date;

import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;
@Alias("PaintedEggAnswer")
public class PaintedEggAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_answer.answerId
     *
     * @mbggenerated
     */
    private String answerid;
    
    private String rightAnswerId;

    public String getRightAnswerId() {
		return rightAnswerId;
	}

	public void setRightAnswerId(String rightAnswerId) {
		this.rightAnswerId = rightAnswerId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_answer.eggId
     *
     * @mbggenerated
     */
    private String eggid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_answer.answer
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_answer.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_answer.createTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_answer.updateTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_answer.answerId
     *
     * @return the value of jc_painted_egg_answer.answerId
     *
     * @mbggenerated
     */
    public String getAnswerid() {
        return answerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_answer.answerId
     *
     * @param answerid the value for jc_painted_egg_answer.answerId
     *
     * @mbggenerated
     */
    public void setAnswerid(String answerid) {
        this.answerid = answerid == null ? null : answerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_answer.eggId
     *
     * @return the value of jc_painted_egg_answer.eggId
     *
     * @mbggenerated
     */
    public String getEggid() {
        return eggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_answer.eggId
     *
     * @param eggid the value for jc_painted_egg_answer.eggId
     *
     * @mbggenerated
     */
    public void setEggid(String eggid) {
        this.eggid = eggid == null ? null : eggid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_answer.answer
     *
     * @return the value of jc_painted_egg_answer.answer
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_answer.answer
     *
     * @param answer the value for jc_painted_egg_answer.answer
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_answer.sort
     *
     * @return the value of jc_painted_egg_answer.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_answer.sort
     *
     * @param sort the value for jc_painted_egg_answer.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_answer.createTime
     *
     * @return the value of jc_painted_egg_answer.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_answer.createTime
     *
     * @param createtime the value for jc_painted_egg_answer.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_answer.updateTime
     *
     * @return the value of jc_painted_egg_answer.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_answer.updateTime
     *
     * @param updatetime the value for jc_painted_egg_answer.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}