package com.jy.entity.jc.paintedEgg;

import java.util.Date;

import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;
@Alias("PaintedEggWiner")
public class PaintedEggWiner {
	private String nick_name;
    public String getNick_name() {
		return nick_name;
	}

	public void setNick_name(String nick_name) {
		this.nick_name = nick_name;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_winner.eggId
     *
     * @mbggenerated
     */
    private String eggid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_winner.user_id
     *
     * @mbggenerated
     */
    private String userId;
    
    private int status;

    public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_winner.luckyNum
     *
     * @mbggenerated
     */
    private Integer luckynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_painted_egg_winner.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_winner.eggId
     *
     * @return the value of jc_painted_egg_winner.eggId
     *
     * @mbggenerated
     */
    public String getEggid() {
        return eggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_winner.eggId
     *
     * @param eggid the value for jc_painted_egg_winner.eggId
     *
     * @mbggenerated
     */
    public void setEggid(String eggid) {
        this.eggid = eggid == null ? null : eggid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_winner.user_id
     *
     * @return the value of jc_painted_egg_winner.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_winner.user_id
     *
     * @param userId the value for jc_painted_egg_winner.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_winner.luckyNum
     *
     * @return the value of jc_painted_egg_winner.luckyNum
     *
     * @mbggenerated
     */
    public Integer getLuckynum() {
        return luckynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_winner.luckyNum
     *
     * @param luckynum the value for jc_painted_egg_winner.luckyNum
     *
     * @mbggenerated
     */
    public void setLuckynum(Integer luckynum) {
        this.luckynum = luckynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_painted_egg_winner.createTime
     *
     * @return the value of jc_painted_egg_winner.createTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_painted_egg_winner.createTime
     *
     * @param createtime the value for jc_painted_egg_winner.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}