package com.jy.entity.jc.jcaccountrechargelog;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;

import java.util.Date;
@Alias("JcAccountRechargeView")
public class JcAccountRechargeView extends BaseEntity{

    private String accountId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account_recharge_view.account_log_id
     *
     * @mbggenerated
     */
    private String accountLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account_recharge_view.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account_recharge_view.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account_recharge_view.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account_recharge_view.balance
     *
     * @mbggenerated
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account_recharge_view.money
     *
     * @mbggenerated
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account_recharge_view.pay_type
     *
     * @mbggenerated
     */
    private Short payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account_recharge_view.pay_log_id
     *
     * @mbggenerated
     */
    private String payLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account_recharge_view.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account_recharge_view.account_log_id
     *
     * @return the value of jc_account_recharge_view.account_log_id
     *
     * @mbggenerated
     */
    public String getAccountLogId() {
        return accountLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account_recharge_view.account_log_id
     *
     * @param accountLogId the value for jc_account_recharge_view.account_log_id
     *
     * @mbggenerated
     */
    public void setAccountLogId(String accountLogId) {
        this.accountLogId = accountLogId == null ? null : accountLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account_recharge_view.user_id
     *
     * @return the value of jc_account_recharge_view.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account_recharge_view.user_id
     *
     * @param userId the value for jc_account_recharge_view.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account_recharge_view.mobile
     *
     * @return the value of jc_account_recharge_view.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account_recharge_view.mobile
     *
     * @param mobile the value for jc_account_recharge_view.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account_recharge_view.nick_name
     *
     * @return the value of jc_account_recharge_view.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account_recharge_view.nick_name
     *
     * @param nickName the value for jc_account_recharge_view.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account_recharge_view.balance
     *
     * @return the value of jc_account_recharge_view.balance
     *
     * @mbggenerated
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account_recharge_view.balance
     *
     * @param balance the value for jc_account_recharge_view.balance
     *
     * @mbggenerated
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account_recharge_view.money
     *
     * @return the value of jc_account_recharge_view.money
     *
     * @mbggenerated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account_recharge_view.money
     *
     * @param money the value for jc_account_recharge_view.money
     *
     * @mbggenerated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account_recharge_view.pay_type
     *
     * @return the value of jc_account_recharge_view.pay_type
     *
     * @mbggenerated
     */
    public Short getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account_recharge_view.pay_type
     *
     * @param payType the value for jc_account_recharge_view.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Short payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account_recharge_view.pay_log_id
     *
     * @return the value of jc_account_recharge_view.pay_log_id
     *
     * @mbggenerated
     */
    public String getPayLogId() {
        return payLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account_recharge_view.pay_log_id
     *
     * @param payLogId the value for jc_account_recharge_view.pay_log_id
     *
     * @mbggenerated
     */
    public void setPayLogId(String payLogId) {
        this.payLogId = payLogId == null ? null : payLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account_recharge_view.create_time
     *
     * @return the value of jc_account_recharge_view.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account_recharge_view.create_time
     *
     * @param createTime the value for jc_account_recharge_view.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }
}