package com.jy.entity.jc.picturerel;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

@Alias("PictureRel")
public class PictureRel extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_picture_rel.rel_id
     *
     * @mbggenerated
     */
    private String relId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_picture_rel.entity_id
     *
     * @mbggenerated
     */
    private String entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_picture_rel.pic_id
     *
     * @mbggenerated
     */
    private String picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_picture_rel.pic_rel_type
     *
     * @mbggenerated
     */
    private Short picRelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_picture_rel.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_picture_rel.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_picture_rel.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_picture_rel.rel_id
     *
     * @return the value of jc_picture_rel.rel_id
     *
     * @mbggenerated
     */
    public String getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_picture_rel.rel_id
     *
     * @param relId the value for jc_picture_rel.rel_id
     *
     * @mbggenerated
     */
    public void setRelId(String relId) {
        this.relId = relId == null ? null : relId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_picture_rel.entity_id
     *
     * @return the value of jc_picture_rel.entity_id
     *
     * @mbggenerated
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_picture_rel.entity_id
     *
     * @param entityId the value for jc_picture_rel.entity_id
     *
     * @mbggenerated
     */
    public void setEntityId(String entityId) {
        this.entityId = entityId == null ? null : entityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_picture_rel.pic_id
     *
     * @return the value of jc_picture_rel.pic_id
     *
     * @mbggenerated
     */
    public String getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_picture_rel.pic_id
     *
     * @param picId the value for jc_picture_rel.pic_id
     *
     * @mbggenerated
     */
    public void setPicId(String picId) {
        this.picId = picId == null ? null : picId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_picture_rel.pic_rel_type
     *
     * @return the value of jc_picture_rel.pic_rel_type
     *
     * @mbggenerated
     */
    public Short getPicRelType() {
        return picRelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_picture_rel.pic_rel_type
     *
     * @param picRelType the value for jc_picture_rel.pic_rel_type
     *
     * @mbggenerated
     */
    public void setPicRelType(Short picRelType) {
        this.picRelType = picRelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_picture_rel.sort
     *
     * @return the value of jc_picture_rel.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_picture_rel.sort
     *
     * @param sort the value for jc_picture_rel.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_picture_rel.create_time
     *
     * @return the value of jc_picture_rel.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_picture_rel.create_time
     *
     * @param createTime the value for jc_picture_rel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_picture_rel.update_time
     *
     * @return the value of jc_picture_rel.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_picture_rel.update_time
     *
     * @param updateTime the value for jc_picture_rel.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}