package com.jy.entity.jc.questionfeedback;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
@Alias("questionFeedback")
public class QuestionFeedback extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_question_feedback.question_id
     *
     * @mbggenerated
     */
    private String questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_question_feedback.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_question_feedback.question
     *
     * @mbggenerated
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_question_feedback.contact
     *
     * @mbggenerated
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_question_feedback.reply_id
     *
     * @mbggenerated
     */
    private String replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_question_feedback.reply_content
     *
     * @mbggenerated
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_question_feedback.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_question_feedback.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_question_feedback.question_id
     *
     * @return the value of jc_question_feedback.question_id
     *
     * @mbggenerated
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_question_feedback.question_id
     *
     * @param questionId the value for jc_question_feedback.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId == null ? null : questionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_question_feedback.user_id
     *
     * @return the value of jc_question_feedback.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_question_feedback.user_id
     *
     * @param userId the value for jc_question_feedback.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_question_feedback.question
     *
     * @return the value of jc_question_feedback.question
     *
     * @mbggenerated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_question_feedback.question
     *
     * @param question the value for jc_question_feedback.question
     *
     * @mbggenerated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_question_feedback.contact
     *
     * @return the value of jc_question_feedback.contact
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_question_feedback.contact
     *
     * @param contact the value for jc_question_feedback.contact
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_question_feedback.reply_id
     *
     * @return the value of jc_question_feedback.reply_id
     *
     * @mbggenerated
     */
    public String getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_question_feedback.reply_id
     *
     * @param replyId the value for jc_question_feedback.reply_id
     *
     * @mbggenerated
     */
    public void setReplyId(String replyId) {
        this.replyId = replyId == null ? null : replyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_question_feedback.reply_content
     *
     * @return the value of jc_question_feedback.reply_content
     *
     * @mbggenerated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_question_feedback.reply_content
     *
     * @param replyContent the value for jc_question_feedback.reply_content
     *
     * @mbggenerated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_question_feedback.create_time
     *
     * @return the value of jc_question_feedback.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_question_feedback.create_time
     *
     * @param createTime the value for jc_question_feedback.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}