package com.jy.entity.jc.jcuserstatis;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

@Alias("JcUserStatis")
public class JcUserStatis extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.strong_point
     *
     * @mbggenerated
     */
    private String strongPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.total_profit_rate
     *
     * @mbggenerated
     */
    private BigDecimal totalProfitRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.total_win_cnt
     *
     * @mbggenerated
     */
    private Integer totalWinCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.total_lost_cnt
     *
     * @mbggenerated
     */
    private Integer totalLostCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.my_buy_cnt
     *
     * @mbggenerated
     */
    private Integer myBuyCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.my_bet_cnt
     *
     * @mbggenerated
     */
    private Integer myBetCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.highest_level
     *
     * @mbggenerated
     */
    private Integer highestLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.total_consumption
     *
     * @mbggenerated
     */
    private Integer totalConsumption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.total_recharge
     *
     * @mbggenerated
     */
    private Integer totalRecharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.total_conversion
     *
     * @mbggenerated
     */
    private Integer totalConversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.total_invite
     *
     * @mbggenerated
     */
    private Integer totalInvite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.total_invite_income
     *
     * @mbggenerated
     */
    private Integer totalInviteIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_statis.total_fd_cnt
     *
     * @mbggenerated
     */
    private Integer totalFdCnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.user_id
     *
     * @return the value of jc_user_statis.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.user_id
     *
     * @param userId the value for jc_user_statis.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.strong_point
     *
     * @return the value of jc_user_statis.strong_point
     *
     * @mbggenerated
     */
    public String getStrongPoint() {
        return strongPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.strong_point
     *
     * @param strongPoint the value for jc_user_statis.strong_point
     *
     * @mbggenerated
     */
    public void setStrongPoint(String strongPoint) {
        this.strongPoint = strongPoint == null ? null : strongPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.total_profit_rate
     *
     * @return the value of jc_user_statis.total_profit_rate
     *
     * @mbggenerated
     */
    public BigDecimal getTotalProfitRate() {
        return totalProfitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.total_profit_rate
     *
     * @param totalProfitRate the value for jc_user_statis.total_profit_rate
     *
     * @mbggenerated
     */
    public void setTotalProfitRate(BigDecimal totalProfitRate) {
        this.totalProfitRate = totalProfitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.total_win_cnt
     *
     * @return the value of jc_user_statis.total_win_cnt
     *
     * @mbggenerated
     */
    public Integer getTotalWinCnt() {
        return totalWinCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.total_win_cnt
     *
     * @param totalWinCnt the value for jc_user_statis.total_win_cnt
     *
     * @mbggenerated
     */
    public void setTotalWinCnt(Integer totalWinCnt) {
        this.totalWinCnt = totalWinCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.total_lost_cnt
     *
     * @return the value of jc_user_statis.total_lost_cnt
     *
     * @mbggenerated
     */
    public Integer getTotalLostCnt() {
        return totalLostCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.total_lost_cnt
     *
     * @param totalLostCnt the value for jc_user_statis.total_lost_cnt
     *
     * @mbggenerated
     */
    public void setTotalLostCnt(Integer totalLostCnt) {
        this.totalLostCnt = totalLostCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.my_buy_cnt
     *
     * @return the value of jc_user_statis.my_buy_cnt
     *
     * @mbggenerated
     */
    public Integer getMyBuyCnt() {
        return myBuyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.my_buy_cnt
     *
     * @param myBuyCnt the value for jc_user_statis.my_buy_cnt
     *
     * @mbggenerated
     */
    public void setMyBuyCnt(Integer myBuyCnt) {
        this.myBuyCnt = myBuyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.my_bet_cnt
     *
     * @return the value of jc_user_statis.my_bet_cnt
     *
     * @mbggenerated
     */
    public Integer getMyBetCnt() {
        return myBetCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.my_bet_cnt
     *
     * @param myBetCnt the value for jc_user_statis.my_bet_cnt
     *
     * @mbggenerated
     */
    public void setMyBetCnt(Integer myBetCnt) {
        this.myBetCnt = myBetCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.highest_level
     *
     * @return the value of jc_user_statis.highest_level
     *
     * @mbggenerated
     */
    public Integer getHighestLevel() {
        return highestLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.highest_level
     *
     * @param highestLevel the value for jc_user_statis.highest_level
     *
     * @mbggenerated
     */
    public void setHighestLevel(Integer highestLevel) {
        this.highestLevel = highestLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.total_consumption
     *
     * @return the value of jc_user_statis.total_consumption
     *
     * @mbggenerated
     */
    public Integer getTotalConsumption() {
        return totalConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.total_consumption
     *
     * @param totalConsumption the value for jc_user_statis.total_consumption
     *
     * @mbggenerated
     */
    public void setTotalConsumption(Integer totalConsumption) {
        this.totalConsumption = totalConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.total_recharge
     *
     * @return the value of jc_user_statis.total_recharge
     *
     * @mbggenerated
     */
    public Integer getTotalRecharge() {
        return totalRecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.total_recharge
     *
     * @param totalRecharge the value for jc_user_statis.total_recharge
     *
     * @mbggenerated
     */
    public void setTotalRecharge(Integer totalRecharge) {
        this.totalRecharge = totalRecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.total_conversion
     *
     * @return the value of jc_user_statis.total_conversion
     *
     * @mbggenerated
     */
    public Integer getTotalConversion() {
        return totalConversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.total_conversion
     *
     * @param totalConversion the value for jc_user_statis.total_conversion
     *
     * @mbggenerated
     */
    public void setTotalConversion(Integer totalConversion) {
        this.totalConversion = totalConversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.create_time
     *
     * @return the value of jc_user_statis.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.create_time
     *
     * @param createTime the value for jc_user_statis.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.update_time
     *
     * @return the value of jc_user_statis.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.update_time
     *
     * @param updateTime the value for jc_user_statis.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.total_invite
     *
     * @return the value of jc_user_statis.total_invite
     *
     * @mbggenerated
     */
    public Integer getTotalInvite() {
        return totalInvite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.total_invite
     *
     * @param totalInvite the value for jc_user_statis.total_invite
     *
     * @mbggenerated
     */
    public void setTotalInvite(Integer totalInvite) {
        this.totalInvite = totalInvite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.total_invite_income
     *
     * @return the value of jc_user_statis.total_invite_income
     *
     * @mbggenerated
     */
    public Integer getTotalInviteIncome() {
        return totalInviteIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.total_invite_income
     *
     * @param totalInviteIncome the value for jc_user_statis.total_invite_income
     *
     * @mbggenerated
     */
    public void setTotalInviteIncome(Integer totalInviteIncome) {
        this.totalInviteIncome = totalInviteIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_statis.total_fd_cnt
     *
     * @return the value of jc_user_statis.total_fd_cnt
     *
     * @mbggenerated
     */
    public Integer getTotalFdCnt() {
        return totalFdCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_statis.total_fd_cnt
     *
     * @param totalFdCnt the value for jc_user_statis.total_fd_cnt
     *
     * @mbggenerated
     */
    public void setTotalFdCnt(Integer totalFdCnt) {
        this.totalFdCnt = totalFdCnt;
    }
}