package com.jy.entity.jc.jcaccount;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

@Alias("JcAccount")
public class JcAccount extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account.balance
     *
     * @mbggenerated
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_account.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account.account_id
     *
     * @return the value of jc_account.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account.account_id
     *
     * @param accountId the value for jc_account.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account.user_id
     *
     * @return the value of jc_account.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account.user_id
     *
     * @param userId the value for jc_account.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account.balance
     *
     * @return the value of jc_account.balance
     *
     * @mbggenerated
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account.balance
     *
     * @param balance the value for jc_account.balance
     *
     * @mbggenerated
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account.create_time
     *
     * @return the value of jc_account.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account.create_time
     *
     * @param createTime the value for jc_account.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account.update_time
     *
     * @return the value of jc_account.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account.update_time
     *
     * @param updateTime the value for jc_account.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_account.oper_id
     *
     * @return the value of jc_account.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_account.oper_id
     *
     * @param operId the value for jc_account.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }
}