package com.jy.entity.jc.matchdict;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

@Alias("MatchDict")
public class MatchDict extends BaseEntity{
    private Integer maxCcNo; //最大场次号
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_dict.comp_id
     *
     * @mbggenerated
     */
    private String compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_dict.comp_name
     *
     * @mbggenerated
     */
    private String compName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_dict.match_type
     *
     * @mbggenerated
     */
    private Short matchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_dict.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_dict.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_match_dict.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_dict.comp_id
     *
     * @return the value of jc_match_dict.comp_id
     *
     * @mbggenerated
     */
    public String getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_dict.comp_id
     *
     * @param compId the value for jc_match_dict.comp_id
     *
     * @mbggenerated
     */
    public void setCompId(String compId) {
        this.compId = compId == null ? null : compId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_dict.comp_name
     *
     * @return the value of jc_match_dict.comp_name
     *
     * @mbggenerated
     */
    public String getCompName() {
        return compName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_dict.comp_name
     *
     * @param compName the value for jc_match_dict.comp_name
     *
     * @mbggenerated
     */
    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_dict.match_type
     *
     * @return the value of jc_match_dict.match_type
     *
     * @mbggenerated
     */
    public Short getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_dict.match_type
     *
     * @param matchType the value for jc_match_dict.match_type
     *
     * @mbggenerated
     */
    public void setMatchType(Short matchType) {
        this.matchType = matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_dict.create_time
     *
     * @return the value of jc_match_dict.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_dict.create_time
     *
     * @param createTime the value for jc_match_dict.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_dict.update_time
     *
     * @return the value of jc_match_dict.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_dict.update_time
     *
     * @param updateTime the value for jc_match_dict.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_match_dict.oper_id
     *
     * @return the value of jc_match_dict.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_match_dict.oper_id
     *
     * @param operId the value for jc_match_dict.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    public Integer getMaxCcNo() {
        return maxCcNo;
    }

    public void setMaxCcNo(Integer maxCcNo) {
        this.maxCcNo = maxCcNo;
    }
}