package com.jy.entity.jc.userlevel;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;
@Alias("userLevel")
public class UserLevel extends BaseEntity {
    private Integer sort;


    private Integer isValid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.math_type
     *
     * @mbggenerated
     */
    private Short matchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.level
     *
     * @mbggenerated
     */
    private Short level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.upgrade_type
     *
     * @mbggenerated
     */
    private Short upgradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.bet_cnt
     *
     * @mbggenerated
     */
    private Integer betCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.win_cnt
     *
     * @mbggenerated
     */
    private Integer winCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.lose_cnt
     *
     * @mbggenerated
     */
    private Integer loseCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.profit_rate
     *
     * @mbggenerated
     */
    private BigDecimal profitRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_level.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.id
     *
     * @return the value of jc_user_level.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.id
     *
     * @param id the value for jc_user_level.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.user_id
     *
     * @return the value of jc_user_level.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.user_id
     *
     * @param userId the value for jc_user_level.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.level
     *
     * @return the value of jc_user_level.level
     *
     * @mbggenerated
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.level
     *
     * @param level the value for jc_user_level.level
     *
     * @mbggenerated
     */
    public void setLevel(Short level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.upgrade_type
     *
     * @return the value of jc_user_level.upgrade_type
     *
     * @mbggenerated
     */
    public Short getUpgradeType() {
        return upgradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.upgrade_type
     *
     * @param upgradeType the value for jc_user_level.upgrade_type
     *
     * @mbggenerated
     */
    public void setUpgradeType(Short upgradeType) {
        this.upgradeType = upgradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.oper_id
     *
     * @return the value of jc_user_level.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.oper_id
     *
     * @param operId the value for jc_user_level.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.bet_cnt
     *
     * @return the value of jc_user_level.bet_cnt
     *
     * @mbggenerated
     */
    public Integer getBetCnt() {
        return betCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.bet_cnt
     *
     * @param betCnt the value for jc_user_level.bet_cnt
     *
     * @mbggenerated
     */
    public void setBetCnt(Integer betCnt) {
        this.betCnt = betCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.win_cnt
     *
     * @return the value of jc_user_level.win_cnt
     *
     * @mbggenerated
     */
    public Integer getWinCnt() {
        return winCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.win_cnt
     *
     * @param winCnt the value for jc_user_level.win_cnt
     *
     * @mbggenerated
     */
    public void setWinCnt(Integer winCnt) {
        this.winCnt = winCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.lose_cnt
     *
     * @return the value of jc_user_level.lose_cnt
     *
     * @mbggenerated
     */
    public Integer getLoseCnt() {
        return loseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.lose_cnt
     *
     * @param loseCnt the value for jc_user_level.lose_cnt
     *
     * @mbggenerated
     */
    public void setLoseCnt(Integer loseCnt) {
        this.loseCnt = loseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.profit_rate
     *
     * @return the value of jc_user_level.profit_rate
     *
     * @mbggenerated
     */
    public BigDecimal getProfitRate() {
        return profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.profit_rate
     *
     * @param profitRate the value for jc_user_level.profit_rate
     *
     * @mbggenerated
     */
    public void setProfitRate(BigDecimal profitRate) {
        this.profitRate = profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.create_time
     *
     * @return the value of jc_user_level.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.create_time
     *
     * @param createTime the value for jc_user_level.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_level.update_time
     *
     * @return the value of jc_user_level.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_level.update_time
     *
     * @param updateTime the value for jc_user_level.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getIsValid() {
        return isValid;
    }

    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    public Short getMatchType() {
        return matchType;
    }

    public void setMatchType(Short matchType) {
        this.matchType = matchType;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }
}