package com.jy.entity.jc.jcuserrank;

import com.jy.entity.base.BaseEntity;
import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
@Alias("JcUserRank")
public class JcUserRank extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_rank.issue
     *
     * @mbggenerated
     */
    private String issue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_rank.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_rank.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_rank.profit_rate
     *
     * @mbggenerated
     */
    private BigDecimal profitRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_rank.win_count
     *
     * @mbggenerated
     */
    private Integer winCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_rank.lose_count
     *
     * @mbggenerated
     */
    private Integer loseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_rank.star
     *
     * @mbggenerated
     */
    private Integer star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_user_rank.attention_count
     *
     * @mbggenerated
     */
    private Integer attentionCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_rank.issue
     *
     * @return the value of jc_user_rank.issue
     *
     * @mbggenerated
     */
    public String getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_rank.issue
     *
     * @param issue the value for jc_user_rank.issue
     *
     * @mbggenerated
     */
    public void setIssue(String issue) {
        this.issue = issue == null ? null : issue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_rank.user_id
     *
     * @return the value of jc_user_rank.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_rank.user_id
     *
     * @param userId the value for jc_user_rank.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_rank.profit_rate
     *
     * @return the value of jc_user_rank.profit_rate
     *
     * @mbggenerated
     */
    public BigDecimal getProfitRate() {
        return profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_rank.profit_rate
     *
     * @param profitRate the value for jc_user_rank.profit_rate
     *
     * @mbggenerated
     */
    public void setProfitRate(BigDecimal profitRate) {
        this.profitRate = profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_rank.win_count
     *
     * @return the value of jc_user_rank.win_count
     *
     * @mbggenerated
     */
    public Integer getWinCount() {
        return winCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_rank.win_count
     *
     * @param winCount the value for jc_user_rank.win_count
     *
     * @mbggenerated
     */
    public void setWinCount(Integer winCount) {
        this.winCount = winCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_rank.lose_count
     *
     * @return the value of jc_user_rank.lose_count
     *
     * @mbggenerated
     */
    public Integer getLoseCount() {
        return loseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_rank.lose_count
     *
     * @param loseCount the value for jc_user_rank.lose_count
     *
     * @mbggenerated
     */
    public void setLoseCount(Integer loseCount) {
        this.loseCount = loseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_rank.star
     *
     * @return the value of jc_user_rank.star
     *
     * @mbggenerated
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_rank.star
     *
     * @param star the value for jc_user_rank.star
     *
     * @mbggenerated
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_user_rank.attention_count
     *
     * @return the value of jc_user_rank.attention_count
     *
     * @mbggenerated
     */
    public Integer getAttentionCount() {
        return attentionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_user_rank.attention_count
     *
     * @param attentionCount the value for jc_user_rank.attention_count
     *
     * @mbggenerated
     */
    public void setAttentionCount(Integer attentionCount) {
        this.attentionCount = attentionCount;
    }
}