package com.jy.entity.jc.adposition;

import org.apache.ibatis.type.Alias;

import java.util.Date;
@Alias("adPosition")
public class AdPosition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_ad_position.ad_id
     *
     * @mbggenerated
     */
    private String adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_ad_position.ad_position_type
     *
     * @mbggenerated
     */
    private Short adPositionType;
    private String adPositionName;
    private String path;
    private String isValid; //是否可用 1可用，0不可用
    private Date updateTime;
    private String keyWord; //关键字查询

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_ad_position.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_ad_position.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_ad_position.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_ad_position.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_ad_position.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_ad_position.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_ad_position.ad_id
     *
     * @return the value of jc_ad_position.ad_id
     *
     * @mbggenerated
     */
    public String getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_ad_position.ad_id
     *
     * @param adId the value for jc_ad_position.ad_id
     *
     * @mbggenerated
     */
    public void setAdId(String adId) {
        this.adId = adId == null ? null : adId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_ad_position.ad_position_type
     *
     * @return the value of jc_ad_position.ad_position_type
     *
     * @mbggenerated
     */
    public Short getAdPositionType() {
        return adPositionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_ad_position.ad_position_type
     *
     * @param adPositionType the value for jc_ad_position.ad_position_type
     *
     * @mbggenerated
     */
    public void setAdPositionType(Short adPositionType) {
        this.adPositionType = adPositionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_ad_position.title
     *
     * @return the value of jc_ad_position.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_ad_position.title
     *
     * @param title the value for jc_ad_position.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_ad_position.comment
     *
     * @return the value of jc_ad_position.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_ad_position.comment
     *
     * @param comment the value for jc_ad_position.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_ad_position.url
     *
     * @return the value of jc_ad_position.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_ad_position.url
     *
     * @param url the value for jc_ad_position.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_ad_position.create_time
     *
     * @return the value of jc_ad_position.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_ad_position.create_time
     *
     * @param createTime the value for jc_ad_position.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_ad_position.oper_id
     *
     * @return the value of jc_ad_position.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_ad_position.oper_id
     *
     * @param operId the value for jc_ad_position.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    public String getAdPositionName() {
        return adPositionName;
    }

    public void setAdPositionName(String adPositionName) {
        this.adPositionName = adPositionName;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getIsValid() {
        return isValid;
    }

    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getKeyWord() {
        return keyWord;
    }

    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }
}